version: '3.8'

services:
  web:
    build: .
    container_name: django_app
    command: >
      sh -c "
             python manage.py migrate &&
             python manage.py createsuperuser --no-input --username admin --email admin@example.com &&
             python manage.py create_tenant --schema_name=tenant1 --name='Tenant 1' --is_active=True --domain-is_primary=True --domain-domain=tenant1.localhost &&
             daphne -b 0.0.0.0 -p 8000 multitenant.asgi:application"
    volumes:
      - .:/app
      - ./staticfiles:/app/staticfiles
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      DJANGO_SETTINGS_MODULE: multitenant.settings
    depends_on:
      - db
      - redis
      - elasticsearch

  db:
    image: postgres:15-alpine
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test
      POSTGRES_DB: multi_tenant_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: redis_cache
    ports:
      - "6379:6379"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.12
    container_name: elasticsearch
    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
    ports:
      - "9200:9200"

volumes:
  postgres_data:
